# Generated by Django 5.1.2 on 2024-10-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorybay_id_alter_log_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybay',
            name='friendly_name',
            field=models.CharField(default='default', max_length=191, unique=True),
            preserve_default=False,
        ),
    ]
