# Generated by Django 5.1.2 on 2024-10-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorybay_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybay',
            name='warehouse_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.warehouse', to_field='name'),
        ),
    ]
