# Generated by Django 5.1.2 on 2024-10-28 15:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_historicalinventory_historicalinventorybay_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='log',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='log',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='log',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.CreateModel(
            name='HistoricalInventoryTransfer',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('quantity', models.PositiveIntegerField()),
                ('transfer_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('from_inventory_bay', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventorybay')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_lot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.productlot')),
                ('to_inventory_bay', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventorybay')),
            ],
            options={
                'verbose_name': 'historical inventory transfer',
                'verbose_name_plural': 'historical inventory transfers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryBayLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('inventory_bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_quantities', to='inventory.inventorybay')),
                ('product_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_bays', to='inventory.productlot')),
            ],
            options={
                'unique_together': {('inventory_bay', 'product_lot')},
            },
        ),
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('from_inventory_bay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='outgoing_transfers', to='inventory.inventorybay')),
                ('product_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='inventory.productlot')),
                ('to_inventory_bay', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incoming_transfers', to='inventory.inventorybay')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalInventory',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
