# Generated by Django 5.1.2 on 2024-11-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorylot_releasedlot_scrappedlot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorylot',
            options={'verbose_name': 'Proxy Model', 'verbose_name_plural': 'Proxy Models'},
        ),
    ]
