# Generated by Django 5.1.2 on 2024-11-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_historicalinventorylot_historicalreleasedlot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalinventorylot',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical inventory lot', 'verbose_name_plural': 'historical inventory lots'},
        ),
        migrations.AlterModelOptions(
            name='inventorylot',
            options={},
        ),
    ]
