# Generated by Django 5.1.2 on 2024-11-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_historicalinventorylot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinventorylot',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinventorylot',
            name='inventory_bay',
        ),
        migrations.RemoveField(
            model_name='historicalinventorylot',
            name='product_lot',
        ),
        migrations.RemoveField(
            model_name='historicalreleasedlot',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalreleasedlot',
            name='inventory_bay',
        ),
        migrations.RemoveField(
            model_name='historicalreleasedlot',
            name='product_lot',
        ),
        migrations.RemoveField(
            model_name='historicalscrappedlot',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalscrappedlot',
            name='inventory_bay',
        ),
        migrations.RemoveField(
            model_name='historicalscrappedlot',
            name='product_lot',
        ),
        migrations.DeleteModel(
            name='InventoryLot',
        ),
        migrations.DeleteModel(
            name='ReleasedLot',
        ),
        migrations.DeleteModel(
            name='ScrappedLot',
        ),
        migrations.DeleteModel(
            name='HistoricalInventoryLot',
        ),
        migrations.DeleteModel(
            name='HistoricalReleasedLot',
        ),
        migrations.DeleteModel(
            name='HistoricalScrappedLot',
        ),
    ]
