# Generated by Django 5.1.2 on 2024-11-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_historicalinventorylot_history_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalinventorybay',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Inventory Bay', 'verbose_name_plural': 'historical Inventory Bays'},
        ),
        migrations.AlterModelOptions(
            name='historicalinventorybaylot',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Inventory Lot', 'verbose_name_plural': 'historical Inventory Lots'},
        ),
        migrations.AlterModelOptions(
            name='historicalinventorytransfer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Inventory Transfer', 'verbose_name_plural': 'historical Inventory Transfers'},
        ),
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Product', 'verbose_name_plural': 'historical Products'},
        ),
        migrations.AlterModelOptions(
            name='historicalproductlot',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Product Lot', 'verbose_name_plural': 'historical Product Lots'},
        ),
        migrations.AlterModelOptions(
            name='historicalwarehouse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Warehouse', 'verbose_name_plural': 'historical Warehouses'},
        ),
        migrations.AlterModelOptions(
            name='inventorybay',
            options={'verbose_name': 'Inventory Bay', 'verbose_name_plural': 'Inventory Bays'},
        ),
        migrations.AlterModelOptions(
            name='inventorybaylot',
            options={'verbose_name': 'Inventory Lot', 'verbose_name_plural': 'Inventory Lots'},
        ),
        migrations.AlterModelOptions(
            name='inventorytransfer',
            options={'verbose_name': 'Inventory Transfer', 'verbose_name_plural': 'Inventory Transfers'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productlot',
            options={'verbose_name': 'Product Lot', 'verbose_name_plural': 'Product Lots'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
    ]
