# Generated by Django 5.1.2 on 2024-11-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_historicalinventorybay_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventorytransfer',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
