# Generated by Django 5.1.2 on 2024-11-15 13:52

from django.db import migrations
from core.operations import CreateView


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_historicalinventorytransfer_comments_and_more'),
    ]

    operations = [
        CreateView(
            db_table="inventory_inventorylotview",
            select=[
                "inventory_inventorybaylot.quantity AS 'Quantity'",
                "inventory_inventorybay.name AS 'Location'",
                "inventory_productlot.lot_number AS 'Lot Number'",
                "inventory_product.name AS 'Catalog Number'"
            ],
            from_table='inventory_inventorybaylot',
            join=[
                CreateView.Join(
                    db_table='inventory_inventorybay',
                    on_conditions=[
                        'inventory_inventorybay.id = inventory_inventorybaylot.inventory_bay_id'
                    ]
                ),
                CreateView.Join(
                    db_table='inventory_productlot',
                    on_conditions=[
                        'inventory_productlot.id = inventory_inventorybaylot.product_lot_id'
                    ]
                ),
                CreateView.Join(
                    db_table='inventory_product',
                    on_conditions=[
                        'inventory_product.id = inventory_productlot.product_name_id'
                    ]
                )
            ],
            where=[
                'inventory_inventorybaylot.quantity <> 0',
                "inventory_inventorybay.name <> 'Released'",
                "inventory_inventorybay.name <> 'Scrapped'"
            ]
        )
    ]
