# Generated by Django 5.1.2 on 2024-12-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_create_inventory_view_20241115_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLotView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(db_column='Quantity', max_length=191)),
                ('location', models.CharField(db_column='Location', max_length=191)),
                ('lot_number', models.CharField(db_column='Lot Nummer', max_length=191)),
                ('catalog_number', models.CharField(db_column='Catalog Number', max_length=191)),
            ],
            options={
                'db_table': 'inventory_inventorylotview',
                'managed': False,
            },
        ),
    ]
